// This file is auto-generated. Do not edit this file.
// Generated from scripts/setup-env.js

export const LOCAL_IP_ADDRESS = '192.168.0.210';
export const DFX_NETWORK = 'playground';
export const CANISTER_ID_INTERNET_IDENTITY = 'rdmx6-jaaaa-aaaaa-aaadq-cai';
export const CANISTER_ID_II_INTEGRATION = '4dz5m-uyaaa-aaaab-qac6a-cai';
export const CANISTER_ID_FRONTEND = '6mce5-laaaa-aaaab-qacsq-cai';
export const CANISTER_ID_BACKEND = '2uurk-ziaaa-aaaab-qacla-cai';
export const EXPO_SCHEME = 'expo-icp';
